# Generated by Django 4.1.5 on 2023-03-02 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/realtor/%Y/%m/%d/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_hired', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
