# Generated by Django 4.1.5 on 2023-03-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='date_hired',
        ),
    ]
