# Generated by Django 4.1.5 on 2023-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtors_date_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='agent_type',
            field=models.CharField(choices=[('Buyers Agent', 'Buyers Agent'), ('Listing Agent', 'Listing Agen'), ('Relocation', 'Relocation'), ('Forclosure', 'Forclosure'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
