# Generated by Django 4.1.5 on 2023-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtors_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='agent_type',
        ),
        migrations.AddField(
            model_name='realtors',
            name='buyers_agent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='forclosure_agent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='listing_agent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='relocation_agent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
