# Generated by Django 4.1.5 on 2023-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_remove_realtors_agent_type_realtors_buyers_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='buyers_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtors',
            name='forclosure_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtors',
            name='listing_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtors',
            name='relocation_agent',
            field=models.BooleanField(default=False),
        ),
    ]
