# Generated by Django 4.1.5 on 2023-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_alter_realtors_buyers_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/realtor/%Y/%m/%d/'),
        ),
    ]
