# Generated by Django 4.1.5 on 2023-03-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_realtors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='photo',
        ),
    ]
