# Generated by Django 4.1.5 on 2023-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
