# Generated by Django 4.1.5 on 2023-02-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_realtor_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='top_seller',
        ),
    ]
