# Generated by Django 4.1.5 on 2023-02-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_remove_realtor_top_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d/'),
        ),
    ]
