# Generated by Django 4.1.5 on 2023-02-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_alter_realtor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
