# Generated by Django 4.1.5 on 2023-03-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0003_alter_chatmessage_user_alter_chatroom_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='chatterId',
        ),
    ]
