# Generated by Django 4.1.5 on 2023-03-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0004_rename_user_chatmessage_chatterid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chatterId',
            new_name='user',
        ),
    ]
