# Generated by Django 4.1.5 on 2023-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0010_remove_chatmessage_seller_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
