# Generated by Django 4.1.5 on 2023-01-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='locations',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='listing',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_constructed_date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
