# Generated by Django 4.1.5 on 2023-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_locations_listing_location_alter_listing_pool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
