# Generated by Django 4.1.5 on 2023-01-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='borough',
            new_name='municipality',
        ),
    ]
