# Generated by Django 4.1.5 on 2023-02-10 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(choices=[('University', 'University'), ('Hospital', 'Hospital'), ('Stadium', 'Stadium'), ('Resturant', 'Resturant'), ('Airport', 'Airport'), ('Tourist', 'Tourist')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32645)),
            ],
        ),
    ]
