# Generated by Django 4.1.5 on 2023-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_pointinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='picture5',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathPicture1',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathPicture2',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedroomPicture1',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedroomPicture2',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
    ]
