# Generated by Django 4.1.5 on 2023-02-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_poi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poi',
            new_name='Pois',
        ),
    ]
