# Generated by Django 4.1.5 on 2023-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Airport', 'Airport'), ('Education Institute', 'Education Institute'), ('Resturant', 'Resturant'), ('Tourist Destination', 'Tourist Destination')], max_length=50),
        ),
    ]
