# Generated by Django 4.1.5 on 2023-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_picture4_remove_listing_picture5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
