# Generated by Django 4.1.5 on 2023-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathroom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
