# Generated by Django 4.1.5 on 2023-02-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathPicture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathPicture2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroomPicture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroomPicture2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y,%m/%d/'),
        ),
    ]
