# Generated by Django 4.1.5 on 2023-02-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_bathpicture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
