# Generated by Django 4.1.5 on 2023-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
