# Generated by Django 4.1.5 on 2023-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_booking_f_name_alter_booking_l_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
