# Generated by Django 4.1.5 on 2023-02-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
