# Generated by Django 4.1.5 on 2023-02-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_booking_seller_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seller',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
