# Generated by Django 4.1.5 on 2023-03-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_booking_booker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
