# Generated by Django 4.1.5 on 2023-01-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
