# Generated by Django 4.1.5 on 2023-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_listing_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
