# Generated by Django 4.1.5 on 2023-03-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
