# Generated by Django 4.1.5 on 2023-03-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
