# Generated by Django 4.1.5 on 2023-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_facebook_link_profile_tiktok_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok_link',
            field=models.CharField(blank=True, default='https://www.tiktok.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link',
            field=models.CharField(blank=True, default='https://www.youtube.com/', max_length=100),
        ),
    ]
